### ISSUE TITLE
Election is not restarted properly

### ISSUE THREAD

**Issue by algomaster99** [kth-tcs/trustfull-demonstrator#24]
Tallying after resetting a voting session does not work now. The `tally` command outputs the following message.
```bash
Exception in thread "main" com.verificatum.protocol.ProtocolError: Attempting to shuffle in a used session!
        at com.verificatum.protocol.mixnet.MixNetElGamalSession.shuffle(MixNetElGamalSession.java:207)
        at com.verificatum.protocol.mixnet.MixNetElGamalSession.mix(MixNetElGamalSession.java:342)
        at com.verificatum.protocol.mixnet.MixNetElGamalSession.mix(MixNetElGamalSession.java:357)
        at com.verificatum.protocol.mixnet.MixNetElGamalTool.processMixing(MixNetElGamalTool.java:961)
        at com.verificatum.protocol.mixnet.MixNetElGamalTool.main(MixNetElGamalTool.java:1151)
```

**Comment by algomaster99** [comment]
I had a meeting with Douglas about this. We first need to delete the session of the entire mix net using `-delete` flag define before we can start tallying again.
